language: python

python:
- 3.6

notifications:
  email: false



install:
# See Dockerfile

# Checkout and install Harmonic PE (latest):
- git clone https://github.com/HASTE-project/HarmonicPE.git
- cd HarmonicPE
- git checkout master
- pip3 install .
- cd ..

# Checkout and install the The Windowed Conformal Model (latest):
# This needs to use -e for the .npy files.
- git clone https://github.com/HASTE-project/windowed-conformal-model.git
- cd windowed-conformal-model
- git checkout master
- pip3 install -e .
- cd ..

- pip install .

# Tests broken on Travis
script:
- pytest tests

before_deploy:
- docker build --no-cache=true -t "benblamey/haste-image-proc:latest" .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

