language: python

notifications:
  email: false

before_install:
  - docker build --no-cache=true -t "benblamey/haste-image-proc:latest" .

script:
- pytest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

