language: python

python:
- 3.6

notifications:
  email: false

install:
  # See Dockerfile
- pip install git+https://github.com/HASTE-project/HarmonicPE.git@master
- pip install git+https://github.com/HASTE-project/HasteStorageClient.git@v0.8
- pip install git+https://github.com/HASTE-project/windowed-conformal-model.git@master

- pip install .

before_install:
  - docker build --no-cache=true -t "benblamey/haste-image-proc:latest" .

script:
- pytest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

